export const US_STATES = [
  { code: "AL", name: "Alabama" },
  { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" },
  { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" },
  { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" },
  { code: "DE", name: "Delaware" },
  { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" },
  { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" },
  { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" },
  { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" },
  { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" },
];

export const EMERGENCY_PHRASES = {
  en: {
    polite: [
      "I am exercising my right to remain silent.",
      "I do not consent to any searches.",
      "Am I free to leave?",
      "I would like to speak to a lawyer.",
      "I am not resisting arrest.",
    ],
    avoid: [
      "I didn't do anything wrong",
      "You can't do this to me",
      "This is harassment",
      "I know my rights",
      "I'm going to sue you",
    ],
  },
  es: {
    polite: [
      "Estoy ejerciendo mi derecho a permanecer en silencio.",
      "No consiento a ningún registro.",
      "¿Soy libre de irme?",
      "Me gustaría hablar con un abogado.",
      "No me estoy resistiendo al arresto.",
    ],
    avoid: [
      "No hice nada malo",
      "No puedes hacerme esto",
      "Esto es acoso",
      "Conozco mis derechos",
      "Te voy a demandar",
    ],
  },
};

export const PRICING = {
  stateGuide: 1.99,
  monthlySubscription: 4.99,
  yearlySubscription: 49.99,
};
